# source 來源: https://ichochy.com/posts/blog/20210612.html

name: Algolia Upload Records
run-name: Algolia Upload Records
on:
  push:
    branches: [main]  # 推送到 master branch 時執行
  workflow_dispatch:  # 手動執行

jobs:
  algolia:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Upload Records
        # 取得程式碼
        uses: feng0530/Algolia-Upload-Records@main
        # 設定環境變數
        env:
          APPLICATION_ID: ${{secrets.APPLICATION_ID}}
          ADMIN_API_KEY: ${{secrets.ADMIN_API_KEY}}
          INDEX_NAME: ${{secrets.INDEX_NAME}}
          FILE_PATH: ${{secrets.FILE_PATH}}